name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        run: yarn deploy